name: exam_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  injectable: ^2.5.0
  get_it:
  retrofit: ^4.6.0
  logger: ^2.6.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.1
  dart_either: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator:
  retrofit_generator: ^9.6.0
  build_runner: ^2.5.4
  json_serializable: ^6.9.5

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/constant/
  filename: app_assets.dart
  field_prefix:
  ignore_comments: true
  classname: AppAssets
