name: exam_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  injectable: ^2.5.0
  get_it: ^7.6.0
  retrofit: ^4.6.0
  logger: ^2.6.0
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1
  awesome_snackbar_content: ^0.1.6
  pinput: ^5.0.1
  flutter_secure_storage: ^9.2.3
  fl_chart: ^1.0.0
  cached_network_image: ^3.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.5.0
  retrofit_generator: ^7.0.8 
  build_runner: ^2.4.13  
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
flutter:
  uses-material-design: true

  assets:
    - assets/images/